### ISSUE TITLE
[suggestion] Use '+' symbol in maximize window button

### ISSUE THREAD

**Issue by DarthWound** [vinceliuice/Yosemite-gtk-theme#1]
Hello, this theme is great!

However same issue than for "macOS Sierra" from B00merang and other macOS like themes:

You should use of '+' instead of the two triangles in the maximize button (hover).
1- because the two arrows stay the same even if window is maximized which is incoherent
2- because arrows are pointing to the right even for people who use buttons at left (same as MacOS)
3- Two arrows are often met as a "fullscreen" rather than as a "maximize" meaning
4- '+' is more neutral and is coherent in any scenario
5- It's what original Mac OSX themes use

PS: it's also true for all your other themes, that I use and love since the beginning, so thank you for your work!

**Comment by vinceliuice** [comment]
Thanks for your advice, my friend!
