### ISSUE TITLE
GTK warnings when launching GTK or Gnome apps from terminal

### ISSUE THREAD

**Issue by wangxa** [vinceliuice/Yosemite-gtk-theme#2]
(gvim:10577): Gtk-WARNING **: Theme parsing error: gtk.css:3458:4: shorthand 'transition' cannot be animated

(gvim:10577): Gtk-WARNING **: Theme parsing error: gtk.css:3458:32: Cannot animate property 'transition-duration'

(gvim:10577): Gtk-WARNING **: Theme parsing error: gtk.css:3467:4: shorthand 'transition' cannot be animated

(gvim:10577): Gtk-WARNING **: Theme parsing error: gtk.css:3467:32: Cannot animate property 'transition-duration'

**Comment by vinceliuice** [comment]
Thanks I'll fix this soon

**Comment by vinceliuice** [comment]
FIxed now! you can download the last one I upload
