### ISSUE TITLE
box-shadow issue

### ISSUE THREAD

**Issue by wangxa** [vinceliuice/Yosemite-gtk-theme#3]
It seems the `box-shadow` for `decoration` and `decoration:backdrop` is inappropriate. See the attached gif.

![peek 2018-01-29 22-32](https://user-images.githubusercontent.com/1250269/35538099-94655726-0544-11e8-8a89-deab34a192e4.gif)

**Comment by vinceliuice** [comment]
Can you tell me what's you system and desktop? then I can test, seems only on gnome-shell the shadow works well

**Comment by wangxa** [comment]
Fedora 27, Gnome-shell under Xserver.

**Comment by vinceliuice** [comment]
Fixed now! You can download the last one
