### ISSUE TITLE
The Gnome-shell issue of the latest commit

### ISSUE THREAD

**Issue by wangxa** [vinceliuice/Yosemite-gtk-theme#4]
Hi, I found a problem in the gnome-shell theme. See the attachment. The first is the Pop-dark-slim's gnome-shell, and the second is that of Yosemite-dark.

![pop-dark-slim](https://user-images.githubusercontent.com/1250269/35706653-8104e910-079e-11e8-9679-5d4f27473149.png)

![yosemite-dark](https://user-images.githubusercontent.com/1250269/35706699-a5e29fb6-079e-11e8-8d42-4e4e2e139115.png)

**Comment by vinceliuice** [comment]
Thanks, I'll fix this

**Comment by vinceliuice** [comment]
Fixed now
