### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by freefreeno** [vinceliuice/Yosemite-gtk-theme#6]
To me this is by far your best Mac style theme. The way the whisker menu has grey and black makes it look better than the all black whisker menus that your using on the newer Mac themes you've been creating. Also thunar looks better darker like this theme to ME than the grey in the side menus like the newer ones your making. Only thing wrong is the xfce panel just like 90 percent of themes I install now days. I request this theme to be updated and left just like this but fix the xfce panel. I want to start creating some themes and learning with your scripts. Some guidance would be greatly appreciated. Oh yea the "selected_bg_color" on the panel being blue doesn't quite look correct so maybe make it a lighter grey ya know just for the xfce panel.

**Comment by vinceliuice** [comment]
This theme is renamed Sierra-compact as a compact version of  Sierra gtk theme
