### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ridamnibjia** [vinceliuice/Yosemite-gtk-theme#8]
When i try to install, i get this error.
Installing Yosemite-light ...
./Install: line 110: glib-compile-resources: command not found
   Installing Yosemite-dark ...
./Install: line 110: glib-compile-resources: command not found
   Installing Yosemite-light-solid ...
./Install: line 110: glib-compile-resources: command not found
   Installing Yosemite-dark-solid ...
./Install: line 110: glib-compile-resources: command not found

**Comment by vinceliuice** [comment]
This theme have moved to https://github.com/vinceliuice/Sierra-gtk-theme, please install from there
